-- ============================================================================
--  PORTOFOLIO MUHAMMAD RIZKI - Supabase Schema + Seed
-- ----------------------------------------------------------------------------
--  CARA PAKAI:
--    1. Buka Supabase Dashboard -> SQL Editor -> New query
--    2. Copy SELURUH isi file ini (Ctrl+A, Ctrl+C di sini), paste, lalu Run
--    3. Selesai. Tabel + RLS + storage bucket + data awal langsung jadi.
--
--  Script ini IDEMPOTENT: aman dijalankan berulang kali, data seed tidak dobel.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 0. HELPER: auto-update kolom updated_at
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- 1. TABEL: profile  (satu baris saja, id selalu 1)
-- ---------------------------------------------------------------------------
create table if not exists public.profile (
  id                 smallint primary key default 1,
  name               text    not null default '',
  role               text    not null default '',
  typing_words       text[]  not null default '{}',
  tagline            text    not null default '',
  bio                text    not null default '',
  email              text    not null default '',
  phone              text    not null default '',
  location           text    not null default '',
  linkedin_url       text    not null default '',
  github_url         text    not null default '',
  photo_url          text    not null default '',
  cv_url             text    not null default '',
  available_for_work boolean not null default true,
  stat_projects      smallint not null default 0,
  stat_years_study   smallint not null default 0,
  updated_at         timestamptz not null default now(),
  constraint profile_single_row check (id = 1)
);

drop trigger if exists trg_profile_updated_at on public.profile;
create trigger trg_profile_updated_at before update on public.profile
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- 2. TABEL: skills  (dikelompokkan per kategori)
-- ---------------------------------------------------------------------------
create table if not exists public.skills (
  id         bigint generated by default as identity primary key,
  category   text   not null,
  items      text[] not null default '{}',
  icon       text   not null default 'code',
  sort_order smallint not null default 0,
  constraint skills_category_unique unique (category)
);

-- ---------------------------------------------------------------------------
-- 3. TABEL: experiences
-- ---------------------------------------------------------------------------
create table if not exists public.experiences (
  id          bigint generated by default as identity primary key,
  title       text not null,
  company     text not null default '',
  date_range  text not null default '',
  description text not null default '',
  tech        text[] not null default '{}',
  sort_order  smallint not null default 0
);

-- ---------------------------------------------------------------------------
-- 4. TABEL: educations
-- ---------------------------------------------------------------------------
create table if not exists public.educations (
  id          bigint generated by default as identity primary key,
  degree      text not null,
  institution text not null default '',
  year_range  text not null default '',
  note        text not null default '',
  sort_order  smallint not null default 0
);

-- ---------------------------------------------------------------------------
-- 5. TABEL: projects  (dikelola lewat CMS /admin)
-- ---------------------------------------------------------------------------
create table if not exists public.projects (
  id            uuid primary key default gen_random_uuid(),
  title         text not null,
  description   text not null default '',
  url           text not null default '',
  repo_url      text not null default '',
  thumbnail_url text not null default '',
  thumbnail_path text not null default '',
  tech          text[] not null default '{}',
  category      text not null default 'Web App',
  project_date  text not null default '',
  featured      boolean not null default false,
  sort_order    smallint not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists projects_sort_idx on public.projects (sort_order asc, created_at desc);

drop trigger if exists trg_projects_updated_at on public.projects;
create trigger trg_projects_updated_at before update on public.projects
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- 6. TABEL: messages  (pesan dari form kontak di landing page)
-- ---------------------------------------------------------------------------
create table if not exists public.messages (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  email      text not null,
  subject    text not null default '',
  body       text not null,
  is_read    boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists messages_created_idx on public.messages (created_at desc);

-- ============================================================================
--  ROW LEVEL SECURITY
--  Publik (anon key) HANYA boleh membaca. Semua tulis/hapus dilakukan
--  server-side lewat service role key, yang otomatis bypass RLS.
-- ============================================================================
alter table public.profile     enable row level security;
alter table public.skills      enable row level security;
alter table public.experiences enable row level security;
alter table public.educations  enable row level security;
alter table public.projects    enable row level security;
alter table public.messages    enable row level security;

drop policy if exists "public read profile"     on public.profile;
drop policy if exists "public read skills"      on public.skills;
drop policy if exists "public read experiences" on public.experiences;
drop policy if exists "public read educations"  on public.educations;
drop policy if exists "public read projects"    on public.projects;

create policy "public read profile"     on public.profile     for select using (true);
create policy "public read skills"      on public.skills      for select using (true);
create policy "public read experiences" on public.experiences for select using (true);
create policy "public read educations"  on public.educations  for select using (true);
create policy "public read projects"    on public.projects    for select using (true);

-- messages: TIDAK ada policy sama sekali -> anon tidak bisa baca maupun tulis.
-- Form kontak dikirim ke /api/messages dan disimpan pakai service role.

-- ============================================================================
--  STORAGE: bucket publik untuk thumbnail project
--  Limit 512 KB per file karena gambar sudah dikompres di browser jadi WebP.
--  Bucket publik -> file bisa dibaca siapa saja tanpa perlu policy tambahan.
--  Upload dilakukan server-side pakai service role (bypass RLS).
-- ============================================================================
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'project-images',
  'project-images',
  true,
  524288,
  array['image/webp', 'image/jpeg', 'image/png']
)
on conflict (id) do update
  set public             = true,
      file_size_limit    = 524288,
      allowed_mime_types = array['image/webp', 'image/jpeg', 'image/png'];

-- ============================================================================
--  SEED DATA
-- ============================================================================

-- 1. PROFILE ---------------------------------------------------------------
insert into public.profile (
  id, name, role, typing_words, tagline, bio,
  email, phone, location, linkedin_url, github_url,
  photo_url, cv_url, available_for_work, stat_projects, stat_years_study
) values (
  1,
  'Muhammad Rizki',
  'Software Engineer',
  array['Software Engineer', 'Web Developer', 'Mobile Developer', 'Fresh Graduate'],
  'Fresh graduate Rekayasa Perangkat Lunak Telkom University. I turn requirements into working products, from database to interface.',
  'Software Engineering graduate from Telkom University, with a vocational software engineering background behind it: seven years of formal training in building software. I have built three projects from requirement to working product, including my final-year project: a Scrum-style project management tool with story points and a kanban board. Comfortable across the stack, and already working the way teams do: Git branching, automation testing with Katalon, and static analysis with SonarCloud inside CI/CD.',
  'mrizki282930@gmail.com',
  '+62 815 812 5370',
  'Bogor, Indonesia',
  'https://www.linkedin.com/in/muhammad-rizki-8b0777253',
  'https://github.com/faizrizki',
  '',
  '/cv-muhammad-rizki.pdf',
  true,
  3,
  7
)
on conflict (id) do nothing;

-- 2. SKILLS ----------------------------------------------------------------
insert into public.skills (category, items, icon, sort_order) values
  ('Languages',            array['JavaScript', 'PHP', 'Dart', 'Java'],                                                      'code',        1),
  ('Web',                  array['React.js (Vite)', 'HTML', 'CSS', 'Express.js', 'PHP Native', 'REST API'],                  'globe',       2),
  ('Mobile & Database',    array['Flutter', 'Dart', 'MySQL', 'Supabase (PostgreSQL)'],                                       'database',    3),
  ('Testing, CI/CD & Deploy', array['Katalon', 'SonarCloud', 'CI/CD', 'Vercel'],                                             'shield-check', 4),
  ('Tools & Design',       array['Git', 'GitHub', 'Figma', 'VS Code', 'UI/UX'],                                              'wrench',      5),
  ('Currently Learning',   array['Python'],                                                                                  'sprout',      6)
on conflict (category) do nothing;

-- 3. EXPERIENCES -----------------------------------------------------------
insert into public.experiences (title, company, date_range, description, tech, sort_order)
select 'Web Design Intern', 'Tunas Solution', 'Jun 2020 - Aug 2020',
       'Designed and built web page layouts with HTML, CSS, and Figma, working to the layouts and revisions the team asked for.',
       array['HTML', 'CSS', 'Figma'], 1
where not exists (
  select 1 from public.experiences where title = 'Web Design Intern' and company = 'Tunas Solution'
);

-- 4. EDUCATIONS ------------------------------------------------------------
insert into public.educations (degree, institution, year_range, note, sort_order)
select 'Bachelor of Software Engineering (S1 Rekayasa Perangkat Lunak)', 'Telkom University', '2022 - 2026',
       'Coursework in software design, database systems, software testing, and system analysis.', 1
where not exists (select 1 from public.educations where institution = 'Telkom University');

insert into public.educations (degree, institution, year_range, note, sort_order)
select 'Vocational High School - Software Engineering (RPL)', 'SMK Informatika Pesat, Bogor', '2019 - 2022', '', 2
where not exists (select 1 from public.educations where institution = 'SMK Informatika Pesat, Bogor');

-- 5. PROJECTS --------------------------------------------------------------
insert into public.projects (title, description, url, repo_url, tech, category, project_date, featured, sort_order)
select 'Project Management Tool',
       'Scrum-style project management application: story points, task management, and a kanban board where work moves through To Do, In Progress, Review, and Done. Built end to end as my final-year project. Demo login: pm@test.com / pm123456',
       'https://fe-project-management.vercel.app', '',
       array['React.js', 'PHP', 'Supabase', 'Vercel'], 'Web App', '2025 - 2026', true, 1
where not exists (select 1 from public.projects where title = 'Project Management Tool');

insert into public.projects (title, description, url, repo_url, tech, category, project_date, featured, sort_order)
select 'Internet Cafe Reservation System',
       'Mobile and web app for internet cafe reservations: booking, payment, and user management. Built the clients, the backend, and the data model.',
       '', '',
       array['Flutter', 'React.js', 'Express.js', 'MySQL'], 'Mobile App', 'Jul 2024 - Jan 2025', true, 2
where not exists (select 1 from public.projects where title = 'Internet Cafe Reservation System');

insert into public.projects (title, description, url, repo_url, tech, category, project_date, featured, sort_order)
select 'E-commerce Platform',
       'E-commerce application with an integrated CMS, so catalogue and content could be managed without touching code.',
       '', '',
       array['PHP', 'JavaScript', 'MySQL'], 'Web App', 'Mar 2023 - May 2023', false, 3
where not exists (select 1 from public.projects where title = 'E-commerce Platform');

-- ============================================================================
--  SELESAI. Cek hasilnya:
-- ============================================================================
select 'profile'     as tabel, count(*) as jumlah from public.profile
union all select 'skills',      count(*) from public.skills
union all select 'experiences', count(*) from public.experiences
union all select 'educations',  count(*) from public.educations
union all select 'projects',    count(*) from public.projects
union all select 'messages',    count(*) from public.messages;
